### PR TITLE
Completions

### PR DESCRIPTION
**Pull request by DanielVoogsgerd**
A created a shell completions generator binary for `branectl`, and `brane-cli`

We can generate autocompletions for the major shells (bash, zsh, fish, right now) by running:
```cargo run --package brane-{ctl,cli} --bin completions```

Right now, it generates the three files in the current working directory, if you have any strong preference I can add some arguments to the generator as well, but considering this is probably only ran from CD I did not particularly feel like making it "pretty".

There is one downside of the current implementation. I had to share the clap arguments between the generator and the main binary. In order to do this I created the `cli.rs` file which both binaries include using the `include!` macro. I could have added it to the `lib.rs`, but that would mean we expose it as a public API, which did not feel right.

### CODE REVIEW

**Comment by Lut99** [comment]
That is pretty cool! :)

I agree, I'm not really such a big fan of the `include!()` to get the common CLI code, but I guess that CLI flags are also ill-suited for a public API.

Is it possible to add it as a common dependency to both binaries? I.e., move `completion` up the tree and then do `mod cli` in both main files? This doesn't add it to the public `lib`, but does import the file as a proper module. Don't know if Cargo is OK doing that from multiple binaries, though (although I don't see why not).

Also, a feature idea: since the idea is that scientists may install the `brane`-binary in their PATH, do we have to do something similar for the autocompletion binaries? Maybe we can have something like a `brane install`-command which sets this up. Might also (finally!) be a good point to create the directory structure under `~/.local/share/brane` and `~/.config/brane`. Would you agree?

**Comment by DanielVoogsgerd** [comment]
> I agree, I'm not really such a big fan of the `include!()` to get the common CLI code, but I guess that CLI flags are also ill-suited for a public API.
>
> Is it possible to add it as a common dependency to both binaries? I.e., move `completion` up the tree and then do `mod cli` in both main files? This doesn't add it to the public `lib`, but does import the file as a proper module. Don't know if Cargo is OK doing that from multiple binaries, though (although I don't see why not).

I tried that, and I didn't get it to work, but structuring this code in general was a giant headache. I will try it again, it should indeed be fine. Just ran out of time yesterday. :disappointed:
 
> Also, a feature idea: since the idea is that scientists may install the `brane`-binary in their PATH, do we have to do something similar for the autocompletion binaries?

Okay, this gets a bit messy since we have multiple shells.

**Bash**
Bash has `$BASH_COMPLETION_USER_DIR` which defaults to `$XDG_DATA_HOME/bash-completion`
system-wide we have `/usr/share/bash-completion/bash_completion` IIRC.

**Zsh**
I think just somewhere in `$FPATH`, but I haven't used zsh in a long time, and a quick search did not yield a defacto standard for user specific directories. System-wide, it should be installed in: `/usr/share/zsh/functions/Completion/{Unix,Linux}`

**Fish**
When installing it as a user:
User specific: `~/.config/fish/completions`
System-wide: `/etc/fish/completions`

When shipping it as a package.
User specific: `$XDG_DATA_HOME/fish/vendor_completions.d`
Systemwide: `/usr/share/fish/vendor_completions.d`

> Maybe we can have something like a `brane install`-command which sets this up.

Yeah, probably a good idea to include a `make install` or such. Creating some packages for the major Linux distributions, should be fairly trivial as well. I can package for Debian, Arch, and NixOS. I haven't tried rpm or whatever RedHat is up to nowadays. 

> Might also (finally!) be a good point to create the directory structure under `~/.local/share/brane` and `~/.config/brane`. Would you agree?

Not entirely sure, what you mean by that. Doesn't `brane` create these directories when adding an instance using `brane instance add`?

**Comment by DanielVoogsgerd** [comment]
> I tried that, and I didn't get it to work, but structuring this code in general was a giant headache. I will try it again, it should indeed be fine. Just ran out of time yesterday. 😞

Yeah, it indeed requires moving `completions.rs` up the tree, which I don't particularly like as it requires an explicit mention of the binary in `Cargo.toml`. It also requires us to reexport the `parse` from clap, but that is easily done. So this works now for `branectl`. I will do brane-cli probably tomorrow.

It is technically possible to do the generation of the completions files in `build.rs` as well, but this is a bit of a headache right now as it requires the following types to a separate crate as `build.rs` can obviously not depend its own crate.
```
use brane_ctl::spec::{
    DownloadServicesSubcommand, GenerateBackendSubcommand, GenerateCertsSubcommand, GenerateNodeSubcommand, InclusiveRange, Pair,
    PolicyInputLanguage, ResolvableNodeKind, StartSubcommand, VersionFix, API_DEFAULT_VERSION,
};
```

I thought I would mentioned it anyway.

**Comment by DanielVoogsgerd** [comment]
> Good ideas, all. I'm ready to merge it as-is, if you agree, and then we could do a separate PR for the install and the packaging. And maybe it's time to finally push the Brane images to Dockerhub, too.

Great, I am ready too. I had to rename the binaries to `brane-completions` and `branectl-completions` as having two identically named binaries in a workspace is a warning and will probably be disallowed in the future.

> With respect to the shells, yeah, that's true. If we just support a few common ones and error on the rest is fine by me, those can always be added later by PR.

They don't even error, we generate all versions we can and the rest are just not there right now.

> That feature can indeed be moved to a generic install that could take care of all that! What I meant is that this install can also take care of setting up paths that the brane binary uses as persistent state. It works, but there have been bugs in the past where it didn't correctly initialize the folders it assumed were there; plus, if we move them to the make install, it also makes sense to move them to a make uninstall (which also plays nice with creating packages)!

Ah, I suspect you are talking about the directories in `$XDG_{CONFIG,DATA}_HOME`. We will have to see. Packages generally don't create anything inside the `/home` that is done at runtime, but we will figure something out.

**Comment by Lut99** [comment]
Perfect, thanks!

**Pull request merged**
