### PR TITLE
chore(deps): Switch to git dependencies to tags

### PR DESCRIPTION
**Pull request by DanielVoogsgerd**
Done for the dependencies:
- [x] lut99/download-rs
- [x] lut99/humanlog-rs
- [x] lut99/names-rs
- [x] lut99/error-trace-rs
- [x] lut99/enum-debug
- [x] epi-project/socksx
- [x] onnovalkering/cwl-rs

Fixes: #107

Only checked by compilation.

### CODE REVIEW

**Comment by Lut99** [comment]
If you wouldn't mind, can you quickly double-check where in the crates this tag is? I'm pretty sure they wouldn't have any changes Brane relies on that aren't tagged, but I also wouldn't put it past myself. Let me know if it's the case for any of the crates and I'll see if it's an important change that needs a tag and do it if so.

If onnovalkering/cwl-rs becomes a problem, then let's just remove the dependency for now. Pretty sure that if there is any code that relies on it, it isn't actually used in practice.

**Comment by DanielVoogsgerd** [comment]
All boxes are checked, and CI is happy. :partying_face:

**Comment by Lut99** [comment]
Ah. So 7ca39e7014080b9063599402badd04e4c27f3bf8 changed the `Cargo.lock`-file to introduce `humanlog` as dev-dependency for `brane-exe`, creating merge conflicts for `Cargo.lock`. Just resolved them but apparently the checks now aren't happy xD checking what's up

**Comment by Lut99** [comment]
Great, `cargo` just needed to update the `Cargo.lock` but couldn't because of `--locked` (so that works!)

Running it locally and updating the lock did the trick. Merging!

**Pull request merged**
