### PR TITLE
chore: Remove meta package

### PR DESCRIPTION
**Pull request by DanielVoogsgerd**
This was needed by the zig build, but we have decided to use native
compilation instead.

Dropping this prevents errors where one only performs an action on the
meta package instead of the workspace when --workspace is omitted.

### CODE REVIEW

**Comment by Lut99** [comment]
Fair enough! Quick question for your consideration: is it worth it to move the `overview`-package to the repo's root? It's there to have an entrypoint to the documentation, but maybe it's not necessary to have / the way we currently have it is fine. What do you think?

Also, licenses and minimum versions are broken again :/ what should we do with that?

**Comment by DanielVoogsgerd** [comment]
The minimal-versions one is just the Github action runner problem #179, should resolve that one, you will see that for all PRs until that one has been merged.

The Cargo deny one is my bad, the licenses were not checked properly because of a missing --workspace flag, precisely the reason behind this PR. But that exposes a different problem.

I think merging the Dependabot updates might resolve that problem. :crossed_fingers:

No need to merge until it becomes green.

**Comment by Lut99** [comment]
OK, fair enough. Then we'll leave it as-is!

**Comment by DanielVoogsgerd** [comment]
@Lut99 All green :)

**Pull request merged**
