### PR TITLE
chore(deps): Bump minimal chrono version

### PR DESCRIPTION
**Pull request by DanielVoogsgerd**
Policy reasoner bumped their minimal version of chrono, so we have to as well.

### CODE REVIEW

**Comment by DanielVoogsgerd** [comment]
Just for reference, it is not like we have to do this for every version update for every dependency, because as long as we don't update our minimal version of a package they cannot change their minimal dependencies in our view. However, this is not the case when pinning the latest version, which we do for policy reasoner by using the main branch. So if that version updates, we will have to as well in a lot of cases.

**Comment by Lut99** [comment]
You mean that the reason we have to update is that `policy-reasoner` pins `chrono` to the lateset version, right? And not necessarily that it's a git-dependency?

If so, can we then also consider changing `policy-reasoner`'s version to be minimal, too?

**Comment by Lut99** [comment]
Also can we draw attention to the fact that all checks pass for this one :smirk: it's been a really long time, Daniel, good work!!

**Comment by DanielVoogsgerd** [comment]
> You mean that the reason we have to update is that `policy-reasoner` pins `chrono` to the lateset version, right? And not necessarily that it's a git-dependency?

Not entirely, `policy-reasoner` does not have a version per se. It only has a branch, which unlike a released version (theoretically, practically with crates.io as well) can be altered. 

So when we push an update to `policy-reasoner`s used branch, we can break its only "version" with respect to anything, but in this case its minimal version of the crate `chrono`.

This normally -- with normal semver releases -- would not be, because if we were compatible with the previous release of the crates minimal dependency versions, a new release would create a higher version of the crate and would not change the minimal version of the crate we would use.
Therefore, we would not "see" the crates dependencies update to a new minimal version, as we use our minimal version of the crate which was obviously not altered.

Boy, that is hard to phrase right. The concept, once you grasp it, is by itself is for the most parts fairly trivial, luckily.

> If so, can we then also consider changing `policy-reasoner`'s version to be minimal, too?

I am not entirely sure what you mean with `policy-reasoners`'s version in this case. I can either interpret it as the version of `chrono` `policy-reasoner` uses. Of the version of `policy-reasoner` that is used by Brane. The first one I already did; in fact, that commit -- I think -- is the primary reason we had to change this dependency.

The second one is a bigger issue, and I was just about to open and issue for that: #<ref>

**Comment by Lut99** [comment]
I see. OK yeah, that makes sense - we're ignoring breaking changes in `policy-reasoner` because we keep breakingly updating its "version". Good explanation!

Let's do this, then. Thanks, @DanielVoogsgerd!

**Pull request merged**
