### PR TITLE
chore(ci): Remove unnecessary runs of CI and update badges

### PR DESCRIPTION
**Pull request by DanielVoogsgerd**
Again a change to CI.

This time not really anything of substance, we just run CI a bit too often which does slow our pipeline if we rebase a lot of pull requests at once :innocent:

Edit: Added an small commit to update the badges and readme resources.

### CODE REVIEW

**Comment by Lut99** [comment]
There's a conflict now :sweat_smile: can you maybe check what it is?

**Comment by DanielVoogsgerd** [comment]
This should be resolved. However, the enum-debug issue will let the minimal version ci check fail unfortunately.

**Comment by Lut99** [comment]
Ow. Wait why is that occurring again? Or will that be fixed once merged?

**Comment by DanielVoogsgerd** [comment]
Unfortunately yes, see #158

**Comment by DanielVoogsgerd** [comment]
Ah, I misread your question. No, let's not. Let's try to fix the underlying enum-debug issue first, this is not very urgent.

**Pull request merged**
